### ISSUE TITLE
[1.15.2] Gardens Solid Blocks

### ISSUE THREAD

**Issue by curlywaffles** [MatrexsVigil/phc2crops#1]
Gardens are not passable like grass.

**Comment by WuzgXY-GitHub** [comment]
That might just be a new setting like it's passable that the special logs in PHC2-Trees

**Comment by Bass2style** [comment]
nothing in the config files about this.

**Comment by Linguardium** [comment]
looking at the code, assuming BushBlock refers to the berry bushes, it should slow but not stop you.

**Comment by Linguardium** [comment]
@curlywaffles can you verify this was fixed in the new version, and if so, close this issue?

**Comment by curlywaffles** [comment]
Confirmed fixed.
