### ISSUE TITLE
[1.15.2] Server error - failed to load correcty

### ISSUE THREAD

**Issue by Argmaster** [MatrexsVigil/phc2crops#11]
I'm trying to set up small but hevily moded minecraft server and i would really love to have your mod included. And here is a problem, this mod doesnt want to take part in my adventure.
I tried to load only some of mods I have with yours and after I found comment on courseforge with similar issue, I tried also loading only your mod. However It still doesnt work.
Here is crash report and I'm ready to provide you any additional knowledge You will require as long as I will be smart enough to do so.
[crash-2020-05-18_18.55.17-server.txt](https://github.com/MatrexsVigil/phc2crops/files/4645526/crash-2020-05-18_18.55.17-server.txt)

**Comment by Linguardium** [comment]
this was fixed in 1.0.5, you are using an old version.

**Comment by Argmaster** [comment]
Thanks then, Im closing
