### ISSUE TITLE
All Garden variations are Solid Blocks 1.14.4-1.0.4.

### ISSUE THREAD

**Issue by GingerbiKinder** [MatrexsVigil/phc2crops#12]
As the title says, all naturally spawning and placed garden variations are acting as solid blocks. Not sure if this is an intended feature or not.

**Comment by Linguardium** [comment]
What version? this was fixed in the 1.15.2 releases but the fix does not seem to have been backported to 1.14

**Comment by GingerbiKinder** [comment]
Yeah, as of 1.14.4-1.0.4. I'm still able to stand on them

**Comment by Linguardium** [comment]
That makes sense. If Pam doesnt get around to backporting the changes, i can PR an update over the next week for her to review.  I know she is probably busy on phc2 trees, Tree generation was changed significantly in 1.16. (luckily crops and food were effectively untouched so it should be very easy to port the other 2 modules over).
