### ISSUE TITLE
Seeds don't drop from grass regardless of config settings

### ISSUE THREAD

**Issue by MokahTGS** [MatrexsVigil/phc2crops#15]
Using the 1.15.2 on a server and seeds are not dropping from grass even if we have them set to in the configs.

Our config setup:

https://pastebin.com/T5y23eym

**Comment by Linguardium** [comment]
are you making sure to change this setting inside the config file that is inside the world folder and _not_ the one inside the regular config folder? there were changes to configs in Forge 1.14+ that moved the configs to the worlds folder (but also seem to create invalid ones in the ./minecraft/config folder (or server_folder/config)

**Comment by MokahTGS** [comment]
Yes, this on a server so the configs are in the default config folder before the world is created.

**Comment by Linguardium** [comment]
can you check that after the world is created, the config in the world/config folder matches the default you set in the configs folder?

**Comment by MokahTGS** [comment]
Have done this already.  All configs are the same.  Marked to drop seeds but no seeds drop in game on our server.
