### ISSUE TITLE
[1.15.2] Right Clicking crops with mystical fertilizer - Mod Interaction: Mystical Agriculture

### ISSUE THREAD

**Issue by TheUntamed** [MatrexsVigil/phc2crops#16]
I'm not sure on which github I should open this ticket, so I will do it on both: https://github.com/BlakeBr0/MysticalAgriculture/issues/328

**Describe the bug**
Right clicking crops (both vanilla and mystical agriculture crops) with mystical fertilizer or fertilized essence doesn't work if pam's right-click harvesting of crops is enabled.
Vanilla bone meal still works.
If right-clicking is disabled the mystical bone meal works again.
If crop right-click harvesting of other mods like Pickle Tweaks or Simple Farming is enabled, the mystical fertilizer works fine.

**To Reproduce**
Plant vanilla seeds and/or mystical seeds from mystical agriculture and right-click it with mystical fertilizer or fertilized essence while pams' harvestcraft crops right-click harvesting is enabled.

**Expected behavior**
The crops should be fertilized or, if its already fully grown, harvested if right-clicked with mystical fertilizer.

**Screenshots / Scripts / Logs**
No logs or meaningful screenshots.

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Forge: 31.2.33
 - Cucumber: 3.0.9
 - Mystical Agriculture: 3.0.9
- Pam's Harvestcraft Crops: 1.0.5

**Comment by andrewsf** [comment]
I believe this could be trivially fixed by [adding an exception alongside the bonemeal one](https://github.com/MatrexsVigil/phc2crops/blob/018dd7e/src/main/java/pam/pamhc2crops/events/harvest/CropHarvest.java#L47)?

Until & unless that happens, edit `config/pamhc2crops.toml` to set:

```
"Enable right-click harvesting for crops" = false
```
