### ISSUE TITLE
[1.15.2] Sweet Potatoe Texture

### ISSUE THREAD

**Issue by curlywaffles** [MatrexsVigil/phc2crops#2]
Not sure if the texture was meant to have the white outline. 
![pamscrops001](https://user-images.githubusercontent.com/58758245/78199364-1616fe00-7451-11ea-9d0d-97fbe6c05c33.PNG)

**Comment by MatrexsVigil** [comment]
My texture itself does not have that outline.  Where are you getting the screenshot?  In JEI?  Something else?

**Comment by curlywaffles** [comment]
Straight from JEI. And in world.

![image](https://user-images.githubusercontent.com/58758245/78723897-e99c2f80-78f1-11ea-9f0d-f39e631f73a6.png)

This is with no other mods installed other than your 3 mods and JEI.

**Comment by VarianArdell** [comment]
can confirm, my sweet potatoes also look like this in game

**Comment by Linguardium** [comment]
can confirm there is a very light antialiasing happening in the texture. applied a solid black background layer and can see the effect in paint.net app
![image](https://user-images.githubusercontent.com/61733861/81030715-a07ec300-8e3e-11ea-977e-a27ae77e9f80.png)

**Comment by Linguardium** [comment]
@curlywaffles can you verify the new version fixes this, and if so, close this?

**Comment by curlywaffles** [comment]
Confirmed fixed.
