### ISSUE TITLE
[Suggestion] Craft cotton into wool instead of string

### ISSUE THREAD

**Issue by MarioSMB** [MatrexsVigil/phc2crops#28]
There are currently two different crops that provide the same item; flax and cotton both craft into string. It may be more fitting for common uses to have cotton be crafted into wool, and allow flax to maintain its individuality as the primary source of string.

**Comment by MarioSMB** [comment]
I'd just like to note here that I am aware that string can be crafted into wool; the issue here is the redundancy of having multiple plants that do the same thing. Cotton may have the potential of being the go-to source of wool if it were to be crafted directly with it.

**Comment by MatrexsVigil** [comment]
The point is to have multiple plants do the same thing though.  HarvestCraft is about having all sorts of different crops, foods, etc even if they overlap.

**Comment by MarioSMB** [comment]
That's fair. I've since removed this mod, so I wish you the best in future developments and hope my other feedback can be considered at some stage.
