### ISSUE TITLE
[Suggestion] Berry bushes

### ISSUE THREAD

**Issue by MarioSMB** [MatrexsVigil/phc2crops#29]
There are a handful of berries in the mod that are designed to be planted as crops currently, such as blackberries. It would be nice to instead have these function similar to sweet berries, in that they're a bush you have to plant on regular grass, and that hurt when walking through them.

**Comment by MatrexsVigil** [comment]
As I said in the cantaloupe comment, maybe if I make a unique crops sub-mod.
