### ISSUE TITLE
[Suggestion] Plantable sweet potatoes

### ISSUE THREAD

**Issue by MarioSMB** [MatrexsVigil/phc2crops#30]
Currently sweet potatoes need to be crafted into seeds that one then plants. Given potatoes and sweet potatoes are very similar naturally, it would make more sense to be able to plant the sweet potato directly and not require a seed item.

**Comment by MatrexsVigil** [comment]
No, it doesn't.  All my crops can plant directly into the ground.  If yours don't, it's another mod causing or changing it.
