### ISSUE TITLE
Config editing gardens

### ISSUE THREAD

**Issue by MRGUY123** [MatrexsVigil/phc2crops#37]
I’m trying to allow frost gardens to spawn in the boreal forest by changing its biome dictionary by adding “SNOWY”. I even removed forest but the shaded gardens still spawned instead of the frost gardens. Is this a bug or am I doing something wrong, if so how can I fix it? Thanks.

**Comment by MatrexsVigil** [comment]
The biomes are hard coded for now and cannot be changed.
