### ISSUE TITLE
Duplicate Config for Right Click Crops

### ISSUE THREAD

**Issue by ghost** [MatrexsVigil/phc2crops#38]
pamhc2crops-1.16.3-1.0.1

You have duplicate options in the config file for enableing Right Click of crops

FeatureConfig has `rightclick_harvest = config.comment("Disable/enable right-click harvesting of crops.")
				.define("Enable right-click harvesting for crops", true);`

RightClickConfig has `crop_right_click = config.comment("Disable/enable right-click harvesting of crops")
				.define("Enable right-click harvesting for crops", true);`

**Comment by MatrexsVigil** [comment]
Hopefully fixed in 1.16.3-1.0.2

**Comment by ghost** [comment]
I kinda meant merge the two options into one as they seem to be the same, but hey ho  :-)
