### ISSUE TITLE
[1.14.4] conflict with other phc2 mods in a dedicated server

### ISSUE THREAD

**Issue by AnxiousPotato** [MatrexsVigil/phc2crops#4]
Minecraft Version: 1.14.4
Forge Version: 28.2.0
Mod Version: pamhc2crops 1.0.4, pamhc2trees 1.0.0, pamhc2foodcore 1.0.2

i'm trying to setup a modded server for a few friends and i, but had some issues regarding two of your mods. i've removed phc2trees and phc2crops but left phc2foodcore and the server ran fine without any issues.

edit: the three mods work fine in singleplayer.

console log (trimmed, lots of optifine spam): https://pastebin.com/vhMUuddB
console log (raw, incase you needed it?): https://pastebin.com/QCvC1HN4
crash report (and mods list): https://pastebin.com/4jV46zFM

**Comment by MatrexsVigil** [comment]
Please try doing this without Optifine and other mods except mine.  Does it still happen?  Thank you for your help.

**Comment by AnxiousPotato** [comment]
i ran the server with only 3 of your mods loaded, and it worked fine!
here's the latest log: https://pastebin.com/ZrCd0VUC

i guess it had conflicts with some other mods installed.. :(
