### ISSUE TITLE
(1.15.2) white_dim config entry does not let features spawn in other dimension.

### ISSUE THREAD

**Issue by TelepathicGrunt** [MatrexsVigil/phc2crops#5]
When I try allowing pam's crops to spawn in world blender's dimension, it seems the config has no effect or isn't being updated with the new value. 

Here's what I have done. let me know if I have done anything wrong.

First, I ran the game to see what ID the dimension gets in the console and in this case, the dimension ID is 4.
```[Server thread/INFO] [ne.mi.co.DimensionManager/DIMS]: Registered dimension world_blender:world_blender of type world_blender:world_blender and id 4```

Next, I closed the game, opened up Pam's config and added the ID of 4 to the white_dim list.
```
["Dimensions Settings"]
	#Enter a dimension id to whitelist feature generation
	white_dim = [0,4]
```

Then I launch the game and check for the plants but non has spawn even when I travel hundreds of blocks. I did place a debugger on world blender's biomes in my IDE and all the world blender's biomes does have Pam's features. My guess is that this line is the issue and didn't update to hold the new whited dimensions.
https://github.com/MatrexsVigil/phc2trees/blob/7bc5ed3d252458d23a1643b8955274eec515797e/src/main/java/com/pam/pamhc2trees/worldgen/ColdFruitTreeFeature.java#L32

I hope this helps! Let me know if you need more info. When you do fix the issue, please consider changing the config from dimension IDs to dimension resourcelocations as IDs were mainly for 1.12 but now, resourcelocations is the way to go for being user friendly and handle any problems if a dimension changes ID somehow.

(This issue also affects phc2tree as well)

**Comment by Linguardium** [comment]
@TelepathicGrunt can you check the new version and if it fixes your issue, close this? (if not, can you confirm and provide info)

**Comment by TelepathicGrunt** [comment]
Yep it works now in latest version. Thank you!
