### ISSUE TITLE
Hwyla / OneProbe shows Wheat as Name

### ISSUE THREAD

**Issue by Bazzi89** [MatrexsVigil/phc2crops#6]
Title says, if u watch the crops, only vanilla wheat is shown in the namefield.

Single- and Multiplayer

**Comment by H4Mm3r** [comment]
Same problem here. Minecraft 1.14.4, phc2crops 1.0.4

**Comment by Bazzi89** [comment]
Is there no solution?

**Comment by ShockPuppet** [comment]
same issue on 1.15.2. HWYLA shows them in the world as wheat seeds.

**Comment by ArMoReDfUrY** [comment]
i am also having this issue but only for planted crops, fruits and nuts on trees are working as intended.
forge 31.1.77
theoneprobe-1.15-2.0.2
pamhc2foodcore-1.15.2-1.0.3
pamhc2crops-1.15.2-1.0.3
pamhc2trees-1.15.2-1.0.3

**Comment by Linguardium** [comment]
@Bazzi89 can you verify the new version fixed this?

**Comment by ArMoReDfUrY** [comment]
iv'e checked a few crops and it works now.
